# path (from the repository root) to sample sheet (TSV format, columns: sample, condition, ...)
samples: configuration/samples.tsv


# path (from the repository root) to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: configuration/units.tsv


# path (from the repository root) to cluster configuration. Parameters for submitting jobs to cluster via qsub
cluster: configuration/cluster.yaml


# Prefix to temporary
# Some files -such as fastq- occupy a lot of space. To avoid space problems during the processing of the pipelines
# we can use the temporary scratch of hpcnfs or the scratch directory of each node.
# Just write the prefix-path where you want to put those files, or write '.' to have them in the workdir.
# By now just fastq files will be located in this folder
# IMPORTANT: if you have running multiple snakemake pipelines with the same tmp folder all the fastq files will be located togeter. Care with the sample names to not be repeated.
tmp: /hpcnfs/scratch/temporary/.snakemake/cutntag


# perform trimming: false or true
# if true go to params-fastp to set desired trimming parameters
trimming: true


# Parameters for the software used
params:
  # Samblaster by default just mark duplicates but doesn't remove them. To remove pcr duplicates add --removeDups here.
  samblaster: ""
  bowtie2: 
    # https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-bjk2kkye.html
    global: "--local --very-sensitive --no-mixed --no-discordant --phred33"
    pe: "-I 10 -X 700"
  samtools:
    # Memory used by every core of samtools (GB). Be careful that 
    # memory x threads is not bigger than the amount of memory assigned to align rule
    memory: 2
  fastp:
    se: "-Q -L"
    pe: "-Q -L --detect_adapter_for_pe"
  macs2:
    pk_calling: "--keep-dup all -m 3 30"
    gsize: mm
    pvalue: 1e-5
    pvalue_broad: 1e-5
    # -log10 pvalue for peak filtering -corresponds to the 8th column of the narrowPeak file. Default 10.
    filt_peaks_pval: 
      - 10
  seacr:
    # select the top X% of regions by AUC
    top_auc: 
      - 0.01
      - 0.025
      - 0.05
      - 0.075
      - 0.1
    # relaxed or stringent
    mode: "stringent"

# Determine the region corresponding to promoters around TSS
promoter:
  # After TSS
  aTSS: 2500
  # Before TSS
  bTSS: 2500

ref:
  # Bowtie index for the alignment of the sample
  index: /hpcnfs/techunits/bioinformatics/refdata/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome
  # Bowtie index for the alignmed of the spike-in, if there is
  index_spike: /hpcnfs/data/DP/dm6/dm6
  # File required by computeGCbias from deeptools
  2bit: /hpcnfs/data/DP/Databases/mm10.2bit
  # Used in computeGCbias to ignore repetitive regions in the calculation
  rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom_mm10.bed
  # File required by bdg2bigwig from ucsc
  chr_sizes: /hpcnfs/data/DP/Databases/mm10.chrom.sizes
  # https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  # 2304947926 --> mm9
  # 2308125349 --> mm10
  egenome_size: 2308125349

# Bam2bigwig params
bam2bigwig:
  # Set the read extension for SE data. For PE data it will be automatically set to the fragment size. To remove this
  # you have to change directly the code inside the rule bam2bigwig
  read_extension: 200
  other: "--binSize 50"
